Cause ImportError from failed dlopen of the rdBase.so shared library to propagate.
Without this, it's very easy to get a SegFault when importing RDKit
binaries into a python interpreter with a UCS2 vs UCS4 symbol
mismatch. For example:

$ python -c "import rdkit.rdBase"
Segmentation fault

A UCS2 vs UCS4 mismatch should throw the more intelligible stack trace:

$ python -c "import rdkit.rdBase"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: /path/to/lib/libboost_python.so.1.59.0: undefined symbol: PyUnicodeUCS2_FromEncodedObject