Fix format-security GCC warning (#984)
In Fedora land, format-security GCC warnings are treated as errors
so the build would fail like this:

In file included from /usr/include/pgsql/server/postgres.h:48:0,
                 from rdkit.h:40,
                 from mol_op.c:33:
mol_op.c:339:19: error: format not a string literal and no format arguments [-Werror=format-security]
     elog(WARNING, t);
                   ^