support building with boost 1.92.0 (#9494)
Fixes build error seen with boost 1.92.0:
```
 error: no member named 'clear' in 'boost::python::detail::final_list_derived_policies<std::list<std::vector<int>>, true>'
  296 |             return DerivedPolicies::clear(container);
      |                    ~~~~~~~~~~~~~~~~~^
```

Due to boostorg/python@c574084154f908a2d14c4c24866982d527c15111