Added updatePropertyCache to 'constructForceField' to avoid error
Error: what():  getImplicitValence() called without preceding call to calcImplicitValence()

Similar to a previous bug, need to calculate implicitvalence before using it.